### ISSUE TITLE
🐛 Bug: [narrow-trails] incorrect roll counts

### ISSUE THREAD

**Issue by jakeklassen** [LearningTypeScript/projects#108]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [X] This is the appropriate issue form for the bug I would like to report.

### Expected

The first test case returns false in 5 rolls instead of 6.

Given the phrasing in the README.md of the `narrow-trails` project:
> After the dice roll actions are completed, decrease both `food` and `water` by 1. If either is `0` then `return false`.

In particular the **is 0**. I'd expect the first test to fail after 5 rolls of 1, not 6. The phrasing would be more accurate to say `if either is less than 0 then return false`, but given the games objective (and phrasing) makes sense, I think we'd actually want to update the tests to reduce the roll counts.

### Actual

The first test fails in 6 rolls instead of 5.

### Impacted Project

Project: `unions-and-literals/narrow-trails`

See the files: `index.test.ts` and `solution.ts`.

### Additional Info

- I only documented the first test case.
- This would require updating the solution file.

Apologies ahead of time if I've just misunderstood the exercise in some way.

**Comment by JoshuaKGoldberg** [comment]
Thanks for the big report! I just got back from a honeymoon and a day later am now testing positive for COVID, so I can't look at it closely right now. But I will look once I'm better!

**Comment by JoshuaKGoldberg** [comment]
Yup, you're right. I misinterpreted my own project 😄 and implemented the solution + tests incorrectly. Thanks for the spot! It should be fixed in #116.
