### ISSUE TITLE
Add a contributors table to the README.md

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#11]
https://github.com/all-contributors/all-contributors is a nice looking tool. I'd like to use it.

Thanks to #10 there's already at least one person to thank 😄

**Comment by fuadop** [comment]
I think this one has to be done by you, since it requries giving permissions to the all-contributors app.

**Comment by JoshuaKGoldberg** [comment]
Ok, this is done (#49, #50)! @fuadop sorry for all the tag notifications. I hope having your profile photo with a bunch of emojis underneath it on the README.md makes up for them! 😄 

![Screenshot of the README.md contributors table including fuadop](https://user-images.githubusercontent.com/3335181/170894222-d3c99f57-18d9-4da8-a88b-ffdcdef34ef8.png)

**Comment by fuadop** [comment]
This is sweet 😻

**Comment by fuadop** [comment]
Thanks @JoshuaKGoldberg ✨
