### ISSUE TITLE
🛠 Tooling: Remove gitmoji from commitlint 😪

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#133]
### Tooling Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22area%3A+tooling) and found none that matched my request.
- [X] This is the appropriate issue form for the tooling issue I would like to report.

### Expected

Although the emojis are cute, I haven't seen other projects use them. And they can be annoying for contributors to type out.

### Actual

I personally have been irked by having to figure out the right gitmoji for various PR types.

Should gitmoji be removed from the commitlint config?

### Additional Info

cc @fuadop

**Comment by fuadop** [comment]
Are you suggesting we remove gitmoji from the PR title linter? @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
I am. But I'm not 100% sure whether we should 😄. Do you have a strong opinion?

**Comment by fuadop** [comment]
I don't have a strong opinion, the emojis look good 😄 and at the same time I sometimes do take a while to figure out what emoji to use 😅 . In my opinion, the emojis looks niceee. I like it.. but I think UX is more important than the UI haha. 👇 

![image](https://user-images.githubusercontent.com/65264054/185009190-c1a67b1b-6161-4e93-943e-18757bf612ab.png)

**Comment by JoshuaKGoldberg** [comment]
It is beautiful 😭 ... but out of empathy for new users who might not know about emoji keyboards or want to wrangle with emoji names, I'm going to go ahead and mark this as accepting PRs. 😢
