### ISSUE TITLE
pr title linter branch restriction

### ISSUE THREAD

**Issue by fuadop** [LearningTypeScript/projects#14]
Hey @JoshuaKGoldberg , I just realized I didn't specify the main branch in the pull_request event of the pr title linter github action. Does it matter ? or it's okay to lint on PR raised on any branch ?

**Comment by JoshuaKGoldberg** [comment]
Ah, good point! Yes let's restrict it to `main`. I like being able to play around with PRs against other branches. 🙂

**Comment by fuadop** [comment]
perfect !.
