### ISSUE TITLE
Find more issue tasks that could be taken by contributors

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#16]
@fuadop, I have to admit, I wasn't expecting people to find this repository so quickly. And I definitely didn't expect anybody to send PRs. Much appreciated, but now I worry that there's not much to do yet for you! 😅 

Most issues I assigned to myself because I expected to have to resolve them myself. But I un-assigned a bunch just now and marked them as 'accepting PRs'. 

Are there other repository maintenance things that could be done? If so: let's file some issues!

**Comment by fuadop** [comment]
Awesome @JoshuaKGoldberg . Thanks 🚀

**Comment by fuadop** [comment]
I saw it on my github feed actually 😅  since I follow you.

**Comment by JoshuaKGoldberg** [comment]
Closing this out as I've filed a few more issues and added template for other things. Always open to more suggestions! ❤️‍🔥
