### ISSUE TITLE
Add markdownlint (or equivalent) to CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#18]
Similar to #17, but for linting `.md` docs. I've historically used https://github.com/DavidAnson/markdownlint but have a sneaking suspicion there's at least one other good equivalent.

As long as it verifies basic linting goodness such as [heading level increments](https://github.com/DavidAnson/markdownlint/blob/d57b477/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time), I'm happy.

**Comment by fuadop** [comment]
About this @JoshuaKGoldberg , I went over the markdownlint-cli repo.. looks like some rules have to be setup in a config file ? Should I read about all the rules ? 🤔 . Or do you already know about the rules you like ?

**Comment by fuadop** [comment]
I think another markdownlint alternative is [remark-js/remark-lint](https://github.com/remarkjs/remark-lint).

**Comment by JoshuaKGoldberg** [comment]
> looks like some rules have to be setup in a config file

Yeah. I'm fine with going along with whatever default rules are enabled, with changes made to match the existing style in the repo (so, roughly the same strategy as #17).

> remark-js/remark-lint, but it doesn't have as much popularity as markdownlint

Looks like markdownlint is the way to go then! 👍
