### ISSUE TITLE
🐛 Bug: [the-shape-of-types] 

### ISSUE THREAD

**Issue by scalixtro** [LearningTypeScript/projects#183]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [X] This is the appropriate issue form for the bug I would like to report.

### Expected

Class `MockHorror` is assignable to exported class `Horror`. 

### Actual

Got an error ` Argument of type 'MockHorror' is not assignable to parameter of type 'Horror & Horror'.
  Type 'MockHorror' is missing the following properties from type 'Horror': #consumed, #consume, doBattle, getPower` when I run the command `npm run tsc -- --watch` in the `the-shape-of-types` project.

### Impacted Project

`projects/classes/the-shape-of-types`

### Additional Info

* I tried copying the `solution.ts` code into `index.ts` to see if there was something wrong with my solution, but the error persisted.

**Comment by JoshuaKGoldberg** [comment]
Hmm, looks like an introduced failure in new versions of TypeScript. It used to be TypeScript understood all the classes -`Demon`, `Horror`, `Sorcerer`- to be coming from the same place, so instances of `Horror` would all be assignable to each other. Newer versions of TypeScript no longer seem to. I'll send a PR to fix. Thanks for reporting @scalixtro!

**Comment by JoshuaKGoldberg** [comment]
This should be fixed if you pull in the latest commits on the `main` branch. Please do post back if that's not the case. Thanks again for reporting @scalixtro!
