### ISSUE TITLE
✍ Typo: [classifying-creatures] various typos

### ISSUE THREAD

**Issue by meganku-msft** [LearningTypeScript/projects#189]
### Typo Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues and pull requests](https://github.com/LearningTypeScript/projects/issues?q=label%3A%22type%3A+typo%22) and found none that matched my issue.
- [X] I have searched the word or phrase in question online to verify it's incorrect.
- [X] This is the appropriate issue form for the typo I would like to report.

### Impacted Project File

classes\classifying-creatures\03-hamster-helpers\README.md

classes\classifying-creatures\02-dog-displays\index.ts

classes\classifying-creatures\03-hamster-helpers\README.md

### What's Wrong?

classes\classifying-creatures\03-hamster-helpers\README.md: `SmallPetFoot` should be `SmallPetFood`.

classes\classifying-creatures\02-dog-displays\index.ts: Comments at top of file are referring to previous exercise; should refer to puppies instead of parrots.

classes\classifying-creatures\03-hamster-helpers\README.md: file descriptions at bottom still refer to "Puppy" code

**Comment by JoshuaKGoldberg** [comment]
Thanks for reporting @meganku-msft! Similar to #190, most of these were fixed by #174 in source code but not on the live site. The last typo is still there though.
