### ISSUE TITLE
✍ Typo: [modifiers-of-the-types] Misnamed function in README.md

### ISSUE THREAD

**Issue by meganku-msft** [LearningTypeScript/projects#190]
### Typo Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues and pull requests](https://github.com/LearningTypeScript/projects/issues?q=label%3A%22type%3A+typo%22) and found none that matched my issue.
- [X] I have searched the word or phrase in question online to verify it's incorrect.
- [X] This is the appropriate issue form for the typo I would like to report.

### Impacted Project File

type-modifiers\modifiers-of-the-types\02-artifact-assertions\README.md

### What's Wrong?

this readme refers to a function called `announceArtifact` instead of `getArtifactType`.

**Comment by JoshuaKGoldberg** [comment]
Thanks for reporting the typo @meganku-msft! This actually was fixed by #174, but I'd neglected to push those updates to the live site. Will do now.
