### ISSUE TITLE
🐛 Bug: [Text Processor] Inconsistent tests expected results

### ISSUE THREAD

**Issue by JoseCrz** [LearningTypeScript/projects#199]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [X] This is the appropriate issue form for the bug I would like to report.

### Expected

Some tests should pass based on the project's specification, examples and other tests results.

### Actual

Some tests fail due to the expected result being incorrect.

### Impacted Project

Arrays -> Text Processor 

### Additional Info

In `projects/arrays/text-processor/src/index.test.ts` there are some inconsistencies in the tests expected results.

For example:

On the test case at lines 31 to 38 we have: 
```tsx
[
  ["ab de", "abc def"],
  { width: 4 },
  [
    ["ab  ", "de  "],
    ["abc ", "def "],
  ],
],
```

We can see that the first element of the texts array `"ab de"` gets split in the expected result: `["ab  ", "de  "],`.

This is also true for the immediate next test at lines 39 to 47

```tsx
[
  ["ab de", "abc def", "abcd ef"],
  { width: 4 },
  [
    ["ab  ", "de  "],
    ["abc ", "def "],
    ["abcd", "ef  "],
  ],
],

```

We can see the first element of the text array `"ab de"` also gets split in the expected result: `["ab  ", "de  "]`.

However, in the test following this one, the expected result is different doesn't follow this pattern. On line 48 we have:

```tsx
[["ab de", "abc def"], { width: 5 }, [["ab de"], ["abc  ", "def  "]]],
```

In this case, the first element of the text array `"ab de"` doesn't get split, instead we have that its corresponding expected result is `["ab de"]` which differs from the previous test cases and ,to my understanding, also differs from the specification of this project.

A gave a quick look an this "inconsistencies" also appear in more test cases like the test on line 49:
```tsx
[["abc def", "abc def"], { width: 8 }, [["abc def "], ["abc def "]]],
```

test on line 66:
```tsx
[["abc def", "abcdefghi"], { width: 8 }, [["abc def "], ["abcdefghi"]]],
```

or tests at lines 73 to 77
```tsx
[["abc def"], { align: "left", width: 7 }, [["abc def"]]],
[["abc def"], { align: "left", width: 8 }, [["abc def "]]],
[["abc def"], { align: "left", width: 9 }, [["abc def  "]]],
[["abc def"], { align: "left", width: 10 }, [["abc def   "]]],
[["abc def"], { align: "left", width: 11 }, [["abc def    "]]],
```

These "inconsistencies" as I'm calling them right now, in turn make some tests fail which I believe shouldn't.

I re-read the project description and specification a couple times but couldn't find anything that suggested this behavior was expected/intentional. An apologize in advance if my reading comprehension baamboozled me.

**Comment by JoshuaKGoldberg** [comment]
Hey @JoseCrz! So sorry for not replying till now (4 months later! 😩). This project's text is tricky and the description I'd put in wasn't very clear - so I kept getting lost in it, losing track, and then not responding.

> However, in the test following this one, the expected result is different doesn't follow this pattern. On line 48 we have:
> 
> ```ts
> [["ab de", "abc def"], { width: 5 }, [["ab de"], ["abc  ", "def  "]]],
> ```

I don't see how that doesn't follow the pattern? 
* `"ab de"` has 5 characters total: `"ab" + " " + "de"`.
* `"abc  "` has 5 characters total: `"abc" + "  "`.
    * `"abc def"` would have been 7 characters, so it can't combine `"abc"` and `"def"`.
* `"def  "` has 5 characters total: `"def" + "  "`.

As an apology for taking so long (and because I think it's useful), #256 adds some more details to the README.md
