### ISSUE TITLE
✍ Typo: [treasure-hunter] Inconsistent property names

### ISSUE THREAD

**Issue by Taliss** [LearningTypeScript/projects#222]
### Typo Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues and pull requests](https://github.com/LearningTypeScript/projects/issues?q=label%3A%22type%3A+typo%22) and found none that matched my issue.
- [X] I have searched the word or phrase in question online to verify it's incorrect.
- [X] This is the appropriate issue form for the typo I would like to report.

### Impacted Project File

```
generics/treasure-hunter/README.md
generics/treasure-hunter/solution.ts
```

### What's Wrong?

Mismatching description inside Readme file.

> Each Buried object can be one of three things:
- Need to check solutions in order to see there is another 4th possible type for `Buried<T>` - `Treasure<T>`. 

Mismatching property names:
- Readme file points to type `Catacomb<T>` with shape `{contents: Buried<T>, type: 'catacomb'}`, but in `solution.ts` instead of `contents` is used `inside` as a property.
- Readme file points to type `TunnelSystem<T>` with shape `{tunnels: Buried<T>[], type: 'tunnels'}`, but in `solution.ts` instead of `tunnels` is used `entrances` as a property.

### Additional Info

Thank  you for the book <3

**Comment by JoshuaKGoldberg** [comment]
Nice spot thanks for the catch - sorry about the typos! <3
