### ISSUE TITLE
"Commitlint on PR Title" task doesn't wrap names in quotes

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#24]
https://github.com/LearningTypeScript/projects/runs/6563248688?check_suite_focus=true

```
echo "⬆️ build(deps-dev): bump ts-jest from 28.0.0 to 28.0.2" | npx commitlint
/home/runner/work/_temp/dafcdb41-af6[5](https://github.com/LearningTypeScript/projects/runs/6563248688?check_suite_focus=true#step:5:6)-4290-b1f3-5d0b31ab7832.sh: line 1: syntax error near unexpected token `('
```

@fuadop looks like PR titles that include a `(` are breaking bash escaping. This should be a one-line fix to add `"` quotes around the title. Do you want to take this on? 🙂  (no worries if you don't have time, I can too!)

**Comment by fuadop** [comment]
ohhh I see

**Comment by fuadop** [comment]
Let me make the change then @JoshuaKGoldberg .
