### ISSUE TITLE
✍ Typo: [system-of-a-clown] typo in solution

### ISSUE THREAD

**Issue by rachel490** [LearningTypeScript/projects#252]
### Typo Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues and pull requests](https://github.com/LearningTypeScript/projects/issues?q=label%3A%22type%3A+typo%22) and found none that matched my issue.
- [X] I have searched the word or phrase in question online to verify it's incorrect.
- [X] This is the appropriate issue form for the typo I would like to report.

### Impacted Project File

/the-type-system/system-of-a-clown/solution.ts

### What's Wrong?

/the-type-system/system-of-a-clown/solution.ts :  the first two if statement's matchingsDescription name should be Krusty and Ronald respectively.

### previous
```js

	// Krusty says: I had a one-man show on Broadway...
	// That's who showed up, one man!
	if (krustyAvailability) {
		guestCount -= 10;
		krustyAvailability = false;
		matchingsDescription += "Bozo will handle the first ten guests.\n";
		lastClown = "Krusty";
		continue;
	}

	// Ronald says: McDonald's donated a large set of computers to a school...
	// They were all Big Macs!
	if (ronaldAvailability) {
		guestCount -= 5;
		ronaldAvailability = false;
		matchingsDescription += "Krusty will handle the next five guests.\n";
		lastClown = "Ronald";
		continue;
	}
```

### fixed
```js

	// Krusty says: I had a one-man show on Broadway...
	// That's who showed up, one man!
	if (krustyAvailability) {
		guestCount -= 10;
		krustyAvailability = false;
		matchingsDescription += "Krusty will handle the first ten guests.\n";
		lastClown = "Krusty";
		continue;
	}

	// Ronald says: McDonald's donated a large set of computers to a school...
	// They were all Big Macs!
	if (ronaldAvailability) {
		guestCount -= 5;
		ronaldAvailability = false;
		matchingsDescription += "Ronald will handle the next five guests.\n";
		lastClown = "Ronald";
		continue;
	}
```

**Comment by JoshuaKGoldberg** [comment]
Nice spot, thanks for reporting @rachel490!

**Comment by JoshuaKGoldberg** [comment]
Whoops, I neglected to mention in #253 that it fixed this issue. ✅
