### ISSUE TITLE
✍ Typo: [the-shape-of-types] Check for Greater than or Equal to instead of Greater thank.

### ISSUE THREAD

**Issue by henrybown** [LearningTypeScript/projects#254]
### Typo Report Checklist

- [x] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues and pull requests](https://github.com/LearningTypeScript/projects/issues?q=label%3A%22type%3A+typo%22) and found none that matched my issue.
- [X] I have searched the word or phrase in question online to verify it's incorrect.
- [X] This is the appropriate issue form for the typo I would like to report.

### Impacted Project File

Either `index.test.ts` or the page on the website.

### What's Wrong?

[The spec](https://www.learningtypescript.com/classes/the-shape-of-types/#specification) for the `doBattle` method states that `if this horror's .getPower() is greater than the opponent's, consumes the opponent`. The tests check for `this.getPower() >= opponent.getPower()`, so the spec should state that.

**Comment by JoshuaKGoldberg** [comment]
Ah, good spot - thanks @henrybown!
