### ISSUE TITLE
🛠 Tooling: <short description of the request>

### ISSUE THREAD

**Issue by rogue0137** [LearningTypeScript/projects#260]
### Tooling Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22area%3A+tooling) and found none that matched my request.
- [X] This is the appropriate issue form for the tooling issue I would like to report.

### Expected

I expected the tests to run and fail when I ran `npm run test -- 1`.

### Actual

I received this error:

```
 FAIL  01-syntactic-sugar/index.test.js
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      at hijackMethod (../../../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:946:32)
      at Object.install (../../../node_modules/@sinonjs/fake-timers/src/fake-timers-src.js:1733:17)
      at FakeTimers.useFakeTimers (../../../node_modules/@jest/fake-timers/build/modernFakeTimers.js:110:36)
``` 

So I went into `jest.config.js`.

The original file is:

```
module.exports = {
	fakeTimers: { enableGlobally: true },
	transform: {
		"^.+\\.(t|j)sx?$": [
			"@swc/jest",
			{
				jsc: {
					target: "es2021",
				},
			},
		],
	},
};
```

I changed it to:

```
module.exports = {
	fakeTimers: { enableGlobally: false },
	transform: {
		"^.+\\.(t|j)sx?$": [
			"@swc/jest",
			{
				jsc: {
					target: "es2021",
				},
			},
		],
	},
};
```

After changing enableGlobally from true to false, my tests failed the way I expected them to. I then fixed the obvious issues in my code and the tests passed. 

### Additional Info

I'm not really sure how to document this finding. Again, it should only affect users with node v19. I didn't try [this](https://github.com/facebook/react-native/issues/35701#issuecomment-1400583545) out, but it was recommended in a post. 

My node version is v19.9.0.

**Comment by JoshuaKGoldberg** [comment]
👋 thanks for filing this @rogue0137! This is new - and looks like perhaps a result of https://github.com/sinonjs/fake-timers/issues/441? Updating `jest` and `ts-jest` to their latest versions seems to fix it.
