### ISSUE TITLE
✍ Typo: [Treasure-Hunter] added more details to the README.md

### ISSUE THREAD

**Issue by jk15162428** [LearningTypeScript/projects#267]
### Typo Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues and pull requests](https://github.com/LearningTypeScript/projects/issues?q=label%3A%22type%3A+typo%22) and found none that matched my issue.
- [X] I have searched the word or phrase in question online to verify it's incorrect.
- [X] This is the appropriate issue form for the typo I would like to report.

### Impacted Project File

projects/generics/treasure-hunter/README.md

### What's Wrong?

The original specification lacks `Treasure` for `Buried` object.

**Comment by JoshuaKGoldberg** [comment]
Good callout, thanks for filing the issue!
