### ISSUE TITLE
Consider moving all projects into a projects/ folder

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#34]
In general I preferred working in repos that have all "source" files nested in some easy directory structure. Commonly that's `src/` for JS/TS projects, or `packages/` for monorepos.

On the other hand, right now this repo just has directories for each chapter, like `arrays/`. If you want to do a wildcard include on, say, all project `package.json`s, you'd have something like `./*/*/package.json`... which would also catch packages in `node_modules/`. You'd need to exclude `node_modules/` manually. Not ideal. 😬 

Nesting chapter folders in a a `projects/` directory would probably would make #2 and similar tasks easier for not having to deal with `node_modules/` excludes.

cc @fuadop in case you have a preference 🙂

**Comment by fuadop** [comment]
This is perfect @JoshuaKGoldberg
