### ISSUE TITLE
Dependabot prefix character limit

### ISSUE THREAD

**Issue by fuadop** [LearningTypeScript/projects#35]
Read -> https://github.com/LearningTypeScript/projects/runs/6594975169

@JoshuaKGoldberg Looks like the commit message prefix of dependabot has to be changed to something shorter 🥲 . The prefix has a limit of 15 characters. 

Probably we change the [gitmoji](https://gitmoji.dev) on the prefix to something shorter like `:art:`.

**Comment by fuadop** [comment]
Yea right !

**Comment by fuadop** [comment]
Well gitmoji looks good 😌 .

**Comment by JoshuaKGoldberg** [comment]
It does 😢 and I've always wanted it...

**Comment by fuadop** [comment]
You could still browse for shorter gitmojis - https://gitmoji.dev , anyone that can go with "build" and a whitespace and won't go over 15 characters 😉

**Comment by fuadop** [comment]
And also we can tweak the pull request title linter to ignore pull requests from dependabot too.

**Comment by JoshuaKGoldberg** [comment]
Oh that's true! I like that - ignoring dependabot. +1

**Comment by fuadop** [comment]
Yep, I think we should go with that then 👍🏾 .

**Comment by fuadop** [comment]
@JoshuaKGoldberg 
Help merge #26 , so I won't need to fix merge conflict again.. since I want to work on the same files.. (dependabot.yml and pull_request_title.yml).

**Comment by fuadop** [comment]
Also can you attach the `accepting:pr` label to this issue 🤔 .

**Comment by JoshuaKGoldberg** [comment]
Oop yes sorry, doing!

**Comment by fuadop** [comment]
Thanks @JoshuaKGoldberg ✨
