### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#4]
...using the fancy new issue forms! Yes!

**Comment by fuadop** [comment]
Do you have any links to those forms? 
These are what I found for this issue and #5

- https://www.talater.com/open-source-templates/
- https://github.com/devspace/awesome-github-templates

**Comment by JoshuaKGoldberg** [comment]
Yes! https://github.com/typescript-eslint/typescript-eslint/pull/4897 resulted in some great issue forms and discussion around them.

I'll probably want to take this one myself, since I haven't yet figured out exactly what I'm ok with people requesting on this repo. I can be pretty picky with issues 😅.
