### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#5]

**Comment by fuadop** [comment]
I think this one looks good. Do you like it ? https://github.com/theos/theos/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by JoshuaKGoldberg** [comment]
Hmm, that one looks very comprehensive and well-suited for a big project with lots of edge cases. Love it for that purpose -- but this repo is a good bit simpler. I think it'd be fine to keep using the format I've gone with in https://raw.githubusercontent.com/typescript-eslint/typescript-eslint/dbcd9e0e14efe6d7474c3422f8cda04ead2414be/.github/pull_request_template.md
