### ISSUE TITLE
📝 Documentation: Add README.md badges for GitHub Actions, Markdownlint, Prettier, and TypeScript

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#51]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22area%3A+tooling) and found none that matched my request.
- [X] This is the appropriate issue form for the tooling issue I would like to report.

### Expected

Right now the README.md only includes a badge for the all-contributors count.

### Actual

Let's add badges there! At the very least, the relevant tools right now are:

* GitHub Actions ("build passing")
* Markdownlint
* Prettier
* TypeScript

### Additional Info

See https://github.com/JoshuaKGoldberg/TypeStat for badge formatting. We can ignore the npm badge as this repo doesn't (yet?) publish to npm.

**Comment by fuadop** [comment]
Typescript badge  ? How ? Is it just like a typescirpt logo ?@JoshuaKGoldberg  
Also for the build passing own.. what CI triggers that ?

**Comment by fuadop** [comment]
Oh I can see the typescript badge on the typestat repo 👍🏾
