### ISSUE TITLE
🛠 Tooling: Verify PRs match the template

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#55]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22area%3A+tooling) and found none that matched my request.
- [X] This is the appropriate issue form for the tooling issue I would like to report.

### Expected

If someone sends a PR that doesn't match `PULL_REQUEST_TEMPLATE.md`'s format, a CI step should complain. I'm thinking this can be similar to the PR title check, but for the body of the PR.

### Actual

Nothing is set up now.

**Comment by fuadop** [comment]
I've been thinking about this @JoshuaKGoldberg . How do we verify this? Do we use a regex to verify it the PR body has the `check list` title, the 3 checkboxes and the overview title ? Is that the way to go ? Or do you think there is a better way to go about it?

**Comment by JoshuaKGoldberg** [comment]
Yeah good question. I don't know of one 😕. Ideally there'd be some standard action somewhere that does it already.

As to how that action would work on the inside... yeah, a regex based on the PR template seems reasonable. It would be cool if someone _(you?)_ wrote a library that turned a string containing some `\n- [ ]` Markdown checkboxes into a regular expression verifying a match. I can't think of anything better! 😄

**Comment by bradzacher** [comment]
Instead of regex you could probably just parse the markdown and walk the AST.

I.e. Create an eslint rule for the issues!

**Comment by JoshuaKGoldberg** [comment]
Ah shoot sorry @fuadop, I missed your response! I _would_ have said I don't have a preference, but... 👀 looks like this was already created!

https://github.com/marketplace/actions/pr-compliance-action

So I'd say let's use that.
