### ISSUE TITLE
🛠 Tooling: Add a tsc check for solutions to CI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#72]
### Tooling Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22area%3A+tooling) and found none that matched my request.
- [X] This is the appropriate issue form for the tooling issue I would like to report.

### Expected

Most projects use Jest tests for their `.test.*` file. That means TypeScript won't type check those files. There should be some additional action/workflow that runs in CI to make sure, if the solution script were used in place of the index file, `tsc` would report no errors.

### Actual

Nothing verifies right now in CI.

### Additional Info

Note that just running `tsc` on ./*/**/*solution* ./*/**/*test*, excluding `node_modules/`, will give compile errors because test files import from `index` files. There'll need to be some logic to copy solution files over to replace index files.

**Comment by fuadop** [comment]
Hey @JoshuaKGoldberg , I don't seem to understand this issue and I would love to help with it, if possible.

**Comment by JoshuaKGoldberg** [comment]
Ah sorry if the OP is unclear, thanks for asking! 

Right now a lot of projects have package.json scripts that look like this (example: `analyzing-dna`):

```json
"scripts": {
  "test": "jest",
  "test:solutions": "cross-env TEST_SOLUTIONS=1 jest"
}
```

Nothing in CI validates that the solution file (typically `solutions.ts`) in those projects passes TypeScript type checking. Someone could send in a PR with solution code that passes Jest tests but has a type error.

So, there should be some new step added to builds that runs `tsc` on all solution code. Does that make sense?

**Comment by JoshuaKGoldberg** [comment]
What do you see as the pros and cons of those two options? 🙂

**Comment by fuadop** [comment]
The cons of augmenting them IMO is if the solutions CI fail, and one runs the test on their local machine and it passes they might be confused. I would add descriptive logs like type errors at /path/to/file.

The pro of augmenting IMO is the speed of CI.

**Comment by JoshuaKGoldberg** [comment]
> if the solutions CI fail, and one runs the test on their local machine and it passes they might be confused

Sorry, I don't follow why this would be likely to happen? Assuming the user has run `npm install`, why would they be different locally vs. on CI?

I see the cons of augmenting as being mostly related to the cons of running the two checks in series:

* Clarity: If the first fails, the second won't even start
* Speed: The second can't start until the first is done.

They could be run in parallel, but the CI images are pretty limited and don't have a lot of cores. Also I'd imagine the output logs would be confusing to read.

In general for CI, I've found it to be better to have a single job/workflow per discrete action/check. In this case that would lean towards adding a new one for `tsc`.
