### ISSUE TITLE
🛠 Tooling: check-solutions.sh should be executable

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/projects#98]
### Tooling Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22area%3A+tooling) and found none that matched my request.
- [X] This is the appropriate issue form for the tooling issue I would like to report.

### Expected

It should be runnable directly as an executable.

### Actual

You need to `chmod +x` it first.

### Additional Info

As discussed in #63.

**Comment by JoshuaKGoldberg** [comment]
Oh, never mind, you did it in the PR! 😄

**Comment by fuadop** [comment]
Yea :smile:
